apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: task-build-packages-run-1620215422667
  namespace: jens
spec:
  params:
  - name: repodir
    value: /workspace/gardenlinux
  - name: giturl
    value: https://github.com/gardenlinux/gardenlinux.git
  - name: committish
    value: main
  - name: ocipath
    value: eu.gcr.io/gardener-project/test/gardenlinux-test
  - name: version_label
    value: latest
  - name: pkg_name
    value: iproute2
  resources: {}
  serviceAccountName: default
  taskRef:
    kind: Task
    name: task-build-packages
